---
# Single instance with ssd gp2 root volume
- name: Provision EC2 
  ec2:
    key_name: library_team
    group: Griendling Site Security Group
    instance_type: t2.medium
    image: ami-6871a115
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 14
        delete_on_termination: yes
    vpc_subnet_id: subnet-ba79ee80
    assign_public_ip: yes
    instance_tags:
      Name: geoblacklight.ecds.me
    count_tag:
      Name: geoblacklight.ecds.me
    exact_count: 1
  register: ec2

- set_fact:
    ec2_ip: "{{ ec2|json_query('tagged_instances[].public_ip') }}"

- debug:
    msg: "{{ ec2 }}"

- name: Add host 
  add_host:
    name: "{{ item }}"
    ansible_ssh_private_key_file: ~/.ssh/library_team.pem
    groups: ec2_group
  loop: "{{ ec2_ip }}"

