---
- hosts: localhost
  
  roles: 
    - { role: provision_ec2 }

- hosts: ec2_group
  user: ec2-user
  become: yes
  environment:
    PATH: /opt/rh/rh-ruby25/root/usr/local/bin:/opt/rh/rh-ruby25/root/usr/bin:{{ ansible_env.PATH }}
    LD_LIBRARY_PATH: /opt/rh/rh-ruby25/root/usr/local/lib64:/opt/rh/rh-ruby25/root/usr/lib64
    MANPATH: /opt/rh/rh-ruby25/root/usr/local/share/man:/opt/rh/rh-ruby25/root/usr/share/man
    PKG_CONFIG_PATH: /opt/rh/rh-ruby25/root/usr/local/lib64/pkgconfig:/opt/rh/rh-ruby25/root/usr/lib64/pkgconfig
    XDG_DATA_DIRS: /opt/rh/rh-ruby25/root/usr/local/share:/opt/rh/rh-ruby25/root/usr/share
  roles: 
    - { role: uclalib_role_apache }
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_samvera_basepackages }
    - { role: install_ruby_scl }
    - { role: uclalib_role_passenger }
    - { role: uclalib_role_yarn }
