---
- hosts: localhost
  vars:
    project_name: geoblacklight
    env_name: test
  roles: 
    - { role: dce_role_provision_ec2, ec2_exact_count: 1 }
    - { role: dce_role_provision_rds }
    - { role: dce_role_rds_mysql }
    - { role: dce_role_end_play }

- hosts: ec2_group
  user: ec2-user
  gather_facts: no
  become: yes
  vars:
#    ruby_version: rh-ruby24
    project_name: geoblacklight
    env_name: test
  vars_files: 
    - roles/emorylib_role_install_ruby_scl/defaults/main.yml

  environment:
    PATH: "{{ ruby_path }}" 
    LD_LIBRARY_PATH: "{{ ruby_ld_path }}"
    MANPATH: "{{ ruby_manpath }}"
    PKG_CONFIG_PATH: "{{ ruby_pkg_config_path }}"
    XDG_DATA_DIRS: "{{ ruby_xdg_data_dirs }}"
  roles: 
    - { role: dce_role_wait_for_gatherfacts }
    - { role: dce_role_end_play } ## ENDing play
    - { role: dce_role_selinux_reboot }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_rhel7repos }
    - { role: uclalib_role_epel }
    - { role: uclalib_role_samvera_basepackages }
    - { role: uclalib_role_pip }
    - { role: emorylib_role_local_mysqldb }
    - { role: emorylib_role_install_ruby_scl }
#    - { role: uclalib_role_passenger }
#    - { role: uclalib_role_yarn }
#    - { role: uclalib_role_samvera_capdeploy } 
