---

# Defines the version of ruby to install
# This version of ruby must match with an RPM file that exists within the UCLA Library's Yum Repo
# Specifiy this during role execution time - otherwise will use the default below
ruby_version: "2.5.1"
