- lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
  register: selinux_result

- name: Reboot if Selinux changes
  shell: "sleep 7 && reboot"
  async: 1
  poll: 0
  when: selinux_result is changed

- include_role:
    name: wait_for_connection
  when: selinux_result is changed
