- name: Set relative path for calling role
  set_fact:
    relative_role_path: "{{ role_path }}"

#- name: Import local project enviroment vars
#  include_role:
#    name: dce_role_project_env

- name: Include vars from target host
  include_vars:
    file: "{{ playbook_dir }}/host_vars/{{ host }}"
