---
# defaults file for dce_role_provision_rds
rds_command: create
rds_instance_type: db.t2.small
rds_db_engine: Aurora - MySQL Compatible
rds_engine_version:
rds_size: 20
rds_publicly_accessible: no
